name: neom_analytics
description: Analytics for Open Neom.
version: 1.3.0
homepage: https://github.com/Cyberneom/neom_analytics
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git

  fl_chart: ^1.1.1
  csv: ^6.0.0
  flutter_animate: ^4.5.2
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
